"""HTML format report generator.

Generates interactive HTML reports with charts and detailed findings.
"""

from datetime import datetime
from typing import Any

from mass.core.findings import Finding, FindingSummary
from mass.core.types import Severity
from mass.compliance.assessor import AssessmentResult


class HtmlFormatter:
    """Generates HTML format reports."""

    SEVERITY_COLORS: dict[Severity, str] = {
        Severity.CRITICAL: "#dc3545",
        Severity.HIGH: "#fd7e14",
        Severity.MEDIUM: "#ffc107",
        Severity.LOW: "#17a2b8",
        Severity.INFO: "#6c757d",
    }

    def __init__(
        self,
        title: str = "MASS Security Report",
        include_charts: bool = True,
    ) -> None:
        """Initialize the HTML formatter.

        Args:
            title: Report title.
            include_charts: Whether to include charts.
        """
        self.title = title
        self.include_charts = include_charts

    def format(
        self,
        findings: list[Finding],
        scan_id: str = "",
        compliance_result: AssessmentResult | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """Generate HTML report from findings.

        Args:
            findings: List of security findings.
            scan_id: Optional scan ID.
            compliance_result: Optional compliance assessment.
            metadata: Optional additional metadata.

        Returns:
            HTML string.
        """
        summary = FindingSummary.from_findings(findings)
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.title}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{self.title}</h1>
            <p class="subtitle">Generated: {generated_at}</p>
            {f'<p class="scan-id">Scan ID: {scan_id}</p>' if scan_id else ''}
        </header>

        <section class="summary">
            <h2>Executive Summary</h2>
            <div class="summary-cards">
                <div class="card total">
                    <span class="number">{summary.total}</span>
                    <span class="label">Total Findings</span>
                </div>
                <div class="card critical">
                    <span class="number">{summary.critical_count}</span>
                    <span class="label">Critical</span>
                </div>
                <div class="card high">
                    <span class="number">{summary.high_count}</span>
                    <span class="label">High</span>
                </div>
                <div class="card medium">
                    <span class="number">{summary.medium_count}</span>
                    <span class="label">Medium</span>
                </div>
                <div class="card low">
                    <span class="number">{summary.low_count}</span>
                    <span class="label">Low</span>
                </div>
                <div class="card info">
                    <span class="number">{summary.info_count}</span>
                    <span class="label">Info</span>
                </div>
            </div>
        </section>

        {self._generate_compliance_section(compliance_result) if compliance_result else ''}

        <section class="findings">
            <h2>Detailed Findings</h2>
            {self._generate_findings_table(findings)}
        </section>

        <section class="findings-detail">
            <h2>Finding Details</h2>
            {self._generate_finding_details(findings)}
        </section>

        <footer>
            <p>Generated by MASS (Model Analysis Security & Safety)</p>
        </footer>
    </div>

    <script>
        {self._get_scripts()}
    </script>
</body>
</html>"""

        return html

    def _get_styles(self) -> str:
        """Get CSS styles."""
        return """
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            background: #f5f5f5;
            color: #333;
        }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        header {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white;
            padding: 40px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .subtitle { opacity: 0.8; }
        .scan-id { font-family: monospace; opacity: 0.7; margin-top: 10px; }

        section { background: white; border-radius: 8px; padding: 30px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h2 { color: #1a1a2e; margin-bottom: 20px; padding-bottom: 10px; border-bottom: 2px solid #eee; }

        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
        }
        .card {
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            color: white;
        }
        .card .number { display: block; font-size: 2.5em; font-weight: bold; }
        .card .label { display: block; font-size: 0.9em; opacity: 0.9; }
        .card.total { background: #1a1a2e; }
        .card.critical { background: #dc3545; }
        .card.high { background: #fd7e14; }
        .card.medium { background: #ffc107; color: #333; }
        .card.low { background: #17a2b8; }
        .card.info { background: #6c757d; }

        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f8f9fa; font-weight: 600; }
        tr:hover { background: #f8f9fa; }

        .severity-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 500;
            color: white;
        }
        .severity-critical { background: #dc3545; }
        .severity-high { background: #fd7e14; }
        .severity-medium { background: #ffc107; color: #333; }
        .severity-low { background: #17a2b8; }
        .severity-info { background: #6c757d; }

        .finding-card {
            border: 1px solid #eee;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
        }
        .finding-card h3 { color: #333; margin-bottom: 10px; }
        .finding-meta { color: #666; font-size: 0.9em; margin-bottom: 15px; }
        .finding-description { background: #f8f9fa; padding: 15px; border-radius: 4px; margin-bottom: 15px; }
        .finding-evidence { margin-top: 15px; }
        .evidence-item { background: #fff3cd; padding: 10px; border-radius: 4px; margin-top: 10px; font-family: monospace; font-size: 0.9em; }

        .compliance-score {
            font-size: 3em;
            font-weight: bold;
            color: #28a745;
        }
        .compliance-score.warning { color: #ffc107; }
        .compliance-score.danger { color: #dc3545; }

        footer { text-align: center; padding: 20px; color: #666; }

        @media (max-width: 768px) {
            .summary-cards { grid-template-columns: repeat(2, 1fr); }
            table { font-size: 0.9em; }
        }
        """

    def _get_scripts(self) -> str:
        """Get JavaScript for interactivity."""
        return """
        document.querySelectorAll('tr[data-finding-id]').forEach(row => {
            row.style.cursor = 'pointer';
            row.addEventListener('click', () => {
                const id = row.dataset.findingId;
                const detail = document.getElementById('detail-' + id);
                if (detail) {
                    detail.scrollIntoView({ behavior: 'smooth' });
                }
            });
        });
        """

    def _generate_findings_table(self, findings: list[Finding]) -> str:
        """Generate findings summary table."""
        if not findings:
            return "<p>No findings detected.</p>"

        rows = []
        for finding in sorted(
            findings, key=lambda f: (
                0 if f.severity == Severity.CRITICAL else
                1 if f.severity == Severity.HIGH else
                2 if f.severity == Severity.MEDIUM else
                3 if f.severity == Severity.LOW else 4
            )
        ):
            severity_class = f"severity-{finding.severity.value}"
            rows.append(f"""
            <tr data-finding-id="{finding.id}">
                <td><span class="severity-badge {severity_class}">{finding.severity.value.upper()}</span></td>
                <td>{finding.title}</td>
                <td>{finding.category.value}</td>
                <td>{finding.component_name}</td>
                <td>{finding.file_path or '-'}</td>
            </tr>
            """)

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Severity</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Component</th>
                    <th>Location</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        """

    def _generate_finding_details(self, findings: list[Finding]) -> str:
        """Generate detailed finding cards."""
        if not findings:
            return ""

        cards = []
        for finding in findings:
            evidence_html = ""
            if finding.evidence:
                evidence_items = []
                for ev in finding.evidence[:3]:  # Limit to 3 evidence items
                    evidence_items.append(
                        f'<div class="evidence-item"><strong>{ev.type}:</strong> {ev.content[:500]}...</div>'
                        if len(ev.content) > 500 else
                        f'<div class="evidence-item"><strong>{ev.type}:</strong> {ev.content}</div>'
                    )
                evidence_html = f'<div class="finding-evidence"><strong>Evidence:</strong>{"".join(evidence_items)}</div>'

            remediation_html = ""
            if finding.remediation:
                remediation_html = f"""
                <div class="finding-remediation">
                    <strong>Remediation:</strong>
                    <p>{finding.remediation.summary}</p>
                </div>
                """

            severity_class = f"severity-{finding.severity.value}"
            cards.append(f"""
            <div class="finding-card" id="detail-{finding.id}">
                <h3><span class="severity-badge {severity_class}">{finding.severity.value.upper()}</span> {finding.title}</h3>
                <div class="finding-meta">
                    Category: {finding.category.value} | Component: {finding.component_name}
                    {f" | File: {finding.file_path}" if finding.file_path else ""}
                    {f":{finding.line_number}" if finding.line_number else ""}
                </div>
                <div class="finding-description">{finding.description}</div>
                {evidence_html}
                {remediation_html}
            </div>
            """)

        return ''.join(cards)

    def _generate_compliance_section(self, result: AssessmentResult) -> str:
        """Generate compliance section."""
        score = result.overall_compliance_score
        score_class = "danger" if score < 50 else "warning" if score < 80 else ""

        framework_rows = []
        for fw, assessment in result.frameworks.items():
            framework_rows.append(f"""
            <tr>
                <td>{fw.value.upper()}</td>
                <td>{assessment.compliance_score:.1f}%</td>
                <td>{assessment.compliant_count}</td>
                <td>{assessment.non_compliant_count}</td>
                <td>{assessment.partial_count}</td>
            </tr>
            """)

        return f"""
        <section class="compliance">
            <h2>Compliance Assessment</h2>
            <div style="text-align: center; margin-bottom: 30px;">
                <span class="compliance-score {score_class}">{score:.1f}%</span>
                <p>Overall Compliance Score</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Framework</th>
                        <th>Score</th>
                        <th>Compliant</th>
                        <th>Non-Compliant</th>
                        <th>Partial</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(framework_rows)}
                </tbody>
            </table>
        </section>
        """
