"""Base probe protocol and registry.

Defines the interface for probes and provides registration/discovery.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import AsyncIterator, Iterator, Any

from mass.core.types import AttackCategory

logger = logging.getLogger(__name__)


class ProbeStatus(str, Enum):
    """Status of a probe execution."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILURE = "failure"
    SKIPPED = "skipped"


@dataclass
class ProbePrompt:
    """A single prompt generated by a probe."""
    text: str
    probe_name: str
    variant: str = ""
    tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def full_id(self) -> str:
        """Get full prompt identifier."""
        if self.variant:
            return f"{self.probe_name}:{self.variant}"
        return self.probe_name


@dataclass
class ProbeResult:
    """Result of a probe execution."""
    prompt: ProbePrompt
    response: str
    is_vulnerable: bool
    confidence: float = 0.0
    detector_name: str = ""
    detection_details: dict[str, Any] = field(default_factory=dict)
    latency_ms: float = 0.0
    error: str | None = None


class BaseProbe(ABC):
    """Base class for all probes.

    Probes generate adversarial prompts to test LLM behavior.
    Each probe focuses on a specific vulnerability category.
    """

    # Class attributes - must be defined by subclasses
    name: str = ""
    description: str = ""
    category: AttackCategory = AttackCategory.JAILBREAK
    tags: list[str] = []

    # Default detectors to use with this probe
    default_detectors: list[str] = []

    # Probe configuration
    active: bool = True
    recommended: bool = False

    def __init__(self, **kwargs: Any):
        """Initialize probe with optional configuration."""
        self.config = kwargs

    @abstractmethod
    def generate_prompts(self) -> Iterator[ProbePrompt]:
        """Generate test prompts.

        Yields:
            ProbePrompt instances for testing.
        """
        ...

    async def generate_prompts_async(self) -> AsyncIterator[ProbePrompt]:
        """Generate test prompts asynchronously.

        Default implementation wraps synchronous generator.
        Override for true async generation.

        Yields:
            ProbePrompt instances for testing.
        """
        for prompt in self.generate_prompts():
            yield prompt

    def get_detectors(self) -> list[str]:
        """Get compatible detector names.

        Returns:
            List of detector names that can evaluate this probe's results.
        """
        return self.default_detectors

    def get_prompt_count(self) -> int:
        """Get the number of prompts this probe generates.

        Returns:
            Number of prompts, or -1 if unknown.
        """
        return -1

    def _create_prompt(
        self,
        text: str,
        variant: str = "",
        tags: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> ProbePrompt:
        """Helper to create a ProbePrompt.

        Args:
            text: Prompt text.
            variant: Variant identifier.
            tags: Additional tags.
            metadata: Additional metadata.

        Returns:
            ProbePrompt instance.
        """
        all_tags = list(self.tags)
        if tags:
            all_tags.extend(tags)

        return ProbePrompt(
            text=text,
            probe_name=self.name,
            variant=variant,
            tags=all_tags,
            metadata=metadata or {},
        )


class ProbeRegistry:
    """Registry for probe discovery and management."""

    def __init__(self):
        """Initialize probe registry."""
        self._probes: dict[str, type[BaseProbe]] = {}
        self._instances: dict[str, BaseProbe] = {}

    def register(self, probe_class: type[BaseProbe]) -> type[BaseProbe]:
        """Register a probe class.

        Args:
            probe_class: Probe class to register.

        Returns:
            The registered class (for use as decorator).
        """
        name = probe_class.name or probe_class.__name__
        self._probes[name] = probe_class
        logger.debug(f"Registered probe: {name}")
        return probe_class

    def get(self, name: str, **kwargs: Any) -> BaseProbe | None:
        """Get a probe instance by name.

        Args:
            name: Probe name.
            **kwargs: Probe configuration.

        Returns:
            Probe instance or None if not found.
        """
        if name in self._instances and not kwargs:
            return self._instances[name]

        probe_class = self._probes.get(name)
        if probe_class:
            instance = probe_class(**kwargs)
            if not kwargs:
                self._instances[name] = instance
            return instance

        return None

    def get_class(self, name: str) -> type[BaseProbe] | None:
        """Get a probe class by name.

        Args:
            name: Probe name.

        Returns:
            Probe class or None if not found.
        """
        return self._probes.get(name)

    def list_probes(self) -> list[str]:
        """List all registered probe names.

        Returns:
            List of probe names.
        """
        return list(self._probes.keys())

    def list_by_category(self, category: AttackCategory) -> list[str]:
        """List probes by attack category.

        Args:
            category: Attack category.

        Returns:
            List of probe names in that category.
        """
        return [
            name for name, cls in self._probes.items()
            if cls.category == category
        ]

    def list_by_tag(self, tag: str) -> list[str]:
        """List probes by tag.

        Args:
            tag: Tag to filter by.

        Returns:
            List of probe names with that tag.
        """
        return [
            name for name, cls in self._probes.items()
            if tag in cls.tags
        ]

    def get_all(self, **kwargs: Any) -> list[BaseProbe]:
        """Get instances of all registered probes.

        Args:
            **kwargs: Probe configuration.

        Returns:
            List of probe instances.
        """
        probes = []
        for name in self._probes:
            probe = self.get(name, **kwargs)
            if probe:
                probes.append(probe)
        return probes

    def get_active(self, **kwargs: Any) -> list[BaseProbe]:
        """Get instances of all active probes.

        Args:
            **kwargs: Probe configuration.

        Returns:
            List of active probe instances.
        """
        return [p for p in self.get_all(**kwargs) if p.active]

    def get_recommended(self, **kwargs: Any) -> list[BaseProbe]:
        """Get instances of recommended probes.

        Args:
            **kwargs: Probe configuration.

        Returns:
            List of recommended probe instances.
        """
        return [p for p in self.get_all(**kwargs) if p.recommended]

    @property
    def count(self) -> int:
        """Get number of registered probes."""
        return len(self._probes)


# Global probe registry
probe_registry = ProbeRegistry()


def register_probe(cls: type[BaseProbe]) -> type[BaseProbe]:
    """Decorator to register a probe class.

    Usage:
        @register_probe
        class MyProbe(BaseProbe):
            name = "my_probe"
            ...
    """
    return probe_registry.register(cls)


def get_probe(name: str, **kwargs: Any) -> BaseProbe | None:
    """Get a probe instance by name from the global registry."""
    return probe_registry.get(name, **kwargs)


def list_probes() -> list[str]:
    """List all registered probes from the global registry."""
    return probe_registry.list_probes()
